import { Command } from "commander";
import nodeFs from "node:fs";
import nodePath from "node:path";
import {
  approveRelationProposal,
  createRelationProposals,
  listRelationDiagnostics,
  listRelationProposals,
  rejectRelationProposal,
  type RelationProposalFile,
  type RelationProposalStatus,
} from "@llm-wiki/kb";
import { logger } from "../utils/logger.js";
import { resolveGlobalOptions, type RawGlobalOptions } from "../utils/global-options.js";

export function makeRelationsCommand(): Command {
  const command = new Command("relations").description(
    "Manage inferred document-relation proposals",
  );

  command
    .command("propose")
    .description("Import versioned relation proposals generated by an agent")
    .requiredOption("--input <path>", "Proposal JSON file")
    .action((options: { input: string }, cmd: Command) => {
      const context = relationContext(cmd);
      const file = nodePath.resolve(options.input);
      const parsed = JSON.parse(nodeFs.readFileSync(file, "utf8")) as RelationProposalFile;
      const created = createRelationProposals(parsed, context);
      logger.success(`Imported ${created.length} pending relation proposal(s).`);
      for (const proposal of created)
        logger.raw(
          `${proposal.id}\t${proposal.sourcePath}\t${proposal.relationType}\t${proposal.targetPath}`,
        );
    });

  command
    .command("list")
    .description("List relation proposals")
    .option("--status <status>", "pending, approved, rejected, or invalid", "pending")
    .option("--json", "Output proposals as JSON", false)
    .action((options: { status: string; json?: boolean }, cmd: Command) => {
      const status = parseStatus(options.status);
      const proposals = listRelationProposals(status, relationContext(cmd));
      if (options.json) process.stdout.write(JSON.stringify(proposals, null, 2) + "\n");
      else if (proposals.length === 0) logger.info(`No ${status} relation proposals.`);
      else
        for (const proposal of proposals)
          logger.raw(
            `${proposal.id}\t${proposal.confidence.toFixed(2)}\t${proposal.sourcePath}\t${proposal.relationType}\t${proposal.targetPath}`,
          );
    });

  command
    .command("approve")
    .argument("<id>", "Proposal id", parseId)
    .action((id: number, _options: unknown, cmd: Command) => {
      const proposal = approveRelationProposal(id, relationContext(cmd));
      logger.success(`Approved relation proposal ${proposal.id}.`);
    });
  command
    .command("reject")
    .argument("<id>", "Proposal id", parseId)
    .action((id: number, _options: unknown, cmd: Command) => {
      const proposal = rejectRelationProposal(id, relationContext(cmd));
      logger.success(`Rejected relation proposal ${proposal.id}.`);
    });
  command
    .command("diagnostics")
    .option("--json", "Output diagnostics as JSON", false)
    .action((options: { json?: boolean }, cmd: Command) => {
      const diagnostics = listRelationDiagnostics(relationContext(cmd));
      if (options.json) process.stdout.write(JSON.stringify(diagnostics, null, 2) + "\n");
      else if (diagnostics.length === 0) logger.info("No unresolved relation references.");
      else
        for (const item of diagnostics)
          logger.raw(
            `${item.sourcePath}:${item.startLine ?? "?"}\t${item.relationType}\t${item.originalTarget}\t${item.reason}`,
          );
    });
  return command;
}

function relationContext(cmd: Command): { projectRoot: string; dbPath: string } {
  const ctx = resolveGlobalOptions(cmd.optsWithGlobals() as RawGlobalOptions);
  return { projectRoot: ctx.root, dbPath: ctx.dbPath };
}

function parseId(value: string): number {
  if (!/^[1-9]\d*$/.test(value)) throw new Error(`Invalid proposal id "${value}".`);
  return Number(value);
}
function parseStatus(value: string): RelationProposalStatus {
  if (!["pending", "approved", "rejected", "invalid"].includes(value))
    throw new Error(`Invalid relation status "${value}".`);
  return value as RelationProposalStatus;
}
