// GENERATED by scripts/gen-pi-models.mjs — do not edit by hand.
// Source: @earendil-works/pi-ai provider catalog (8 providers supported by the pi sidecar).

export interface PiModelOption {
  id: string;
  name: string;
  contextWindow?: number;
  reasoning: boolean;
}

export interface PiProviderOption {
  value: string;
  label: string;
  envVar: string;
  models: PiModelOption[];
}

export const anthropicModels: PiModelOption[] = [
  { id: "claude-fable-5", name: "Claude Fable 5", contextWindow: 1000000, reasoning: true },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5 (latest)",
    contextWindow: 200000,
    reasoning: true,
  },
  {
    id: "claude-haiku-4-5-20251001",
    name: "Claude Haiku 4.5",
    contextWindow: 200000,
    reasoning: true,
  },
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5 (latest)",
    contextWindow: 200000,
    reasoning: true,
  },
  {
    id: "claude-opus-4-5-20251101",
    name: "Claude Opus 4.5",
    contextWindow: 200000,
    reasoning: true,
  },
  { id: "claude-opus-4-6", name: "Claude Opus 4.6", contextWindow: 1000000, reasoning: true },
  { id: "claude-opus-4-7", name: "Claude Opus 4.7", contextWindow: 1000000, reasoning: true },
  { id: "claude-opus-4-8", name: "Claude Opus 4.8", contextWindow: 1000000, reasoning: true },
  { id: "claude-opus-5", name: "Claude Opus 5", contextWindow: 1000000, reasoning: true },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5 (latest)",
    contextWindow: 1000000,
    reasoning: true,
  },
  {
    id: "claude-sonnet-4-5-20250929",
    name: "Claude Sonnet 4.5",
    contextWindow: 1000000,
    reasoning: true,
  },
  { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", contextWindow: 1000000, reasoning: true },
  { id: "claude-sonnet-5", name: "Claude Sonnet 5", contextWindow: 1000000, reasoning: true },
];

export const openaiModels: PiModelOption[] = [
  { id: "gpt-4", name: "GPT-4", contextWindow: 8192, reasoning: false },
  { id: "gpt-4-turbo", name: "GPT-4 Turbo", contextWindow: 128000, reasoning: false },
  { id: "gpt-4.1", name: "GPT-4.1", contextWindow: 1047576, reasoning: false },
  { id: "gpt-4.1-mini", name: "GPT-4.1 mini", contextWindow: 1047576, reasoning: false },
  { id: "gpt-4.1-nano", name: "GPT-4.1 nano", contextWindow: 1047576, reasoning: false },
  { id: "gpt-4o", name: "GPT-4o", contextWindow: 128000, reasoning: false },
  { id: "gpt-4o-2024-05-13", name: "GPT-4o (2024-05-13)", contextWindow: 128000, reasoning: false },
  { id: "gpt-4o-2024-08-06", name: "GPT-4o (2024-08-06)", contextWindow: 128000, reasoning: false },
  { id: "gpt-4o-2024-11-20", name: "GPT-4o (2024-11-20)", contextWindow: 128000, reasoning: false },
  { id: "gpt-4o-mini", name: "GPT-4o mini", contextWindow: 128000, reasoning: false },
  { id: "gpt-5", name: "GPT-5", contextWindow: 400000, reasoning: true },
  { id: "gpt-5-chat-latest", name: "GPT-5 Chat Latest", contextWindow: 128000, reasoning: false },
  { id: "gpt-5-mini", name: "GPT-5 Mini", contextWindow: 400000, reasoning: true },
  { id: "gpt-5-nano", name: "GPT-5 Nano", contextWindow: 400000, reasoning: true },
  { id: "gpt-5-pro", name: "GPT-5 Pro", contextWindow: 400000, reasoning: true },
  { id: "gpt-5.1", name: "GPT-5.1", contextWindow: 400000, reasoning: true },
  { id: "gpt-5.2", name: "GPT-5.2", contextWindow: 400000, reasoning: true },
  { id: "gpt-5.2-chat-latest", name: "GPT-5.2 Chat", contextWindow: 128000, reasoning: true },
  { id: "gpt-5.2-pro", name: "GPT-5.2 Pro", contextWindow: 400000, reasoning: true },
  {
    id: "gpt-5.3-chat-latest",
    name: "GPT-5.3 Chat (latest)",
    contextWindow: 128000,
    reasoning: false,
  },
  { id: "gpt-5.3-codex", name: "GPT-5.3 Codex", contextWindow: 400000, reasoning: true },
  {
    id: "gpt-5.3-codex-spark",
    name: "GPT-5.3 Codex Spark",
    contextWindow: 128000,
    reasoning: true,
  },
  { id: "gpt-5.4", name: "GPT-5.4", contextWindow: 272000, reasoning: true },
  { id: "gpt-5.4-mini", name: "GPT-5.4 mini", contextWindow: 400000, reasoning: true },
  { id: "gpt-5.4-nano", name: "GPT-5.4 nano", contextWindow: 400000, reasoning: true },
  { id: "gpt-5.4-pro", name: "GPT-5.4 Pro", contextWindow: 1050000, reasoning: true },
  { id: "gpt-5.5", name: "GPT-5.5", contextWindow: 272000, reasoning: true },
  { id: "gpt-5.5-pro", name: "GPT-5.5 Pro", contextWindow: 1050000, reasoning: true },
  { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", contextWindow: 272000, reasoning: true },
  { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", contextWindow: 272000, reasoning: true },
  { id: "gpt-5.6-terra", name: "GPT-5.6 Terra", contextWindow: 272000, reasoning: true },
  { id: "gpt-realtime-2.1", name: "GPT-Realtime-2.1", contextWindow: 128000, reasoning: true },
  { id: "o1", name: "o1", contextWindow: 200000, reasoning: true },
  { id: "o1-pro", name: "o1-pro", contextWindow: 200000, reasoning: true },
  { id: "o3", name: "o3", contextWindow: 200000, reasoning: true },
  { id: "o3-mini", name: "o3-mini", contextWindow: 200000, reasoning: true },
  { id: "o3-pro", name: "o3-pro", contextWindow: 200000, reasoning: true },
  { id: "o4-mini", name: "o4-mini", contextWindow: 200000, reasoning: true },
];

export const googleModels: PiModelOption[] = [
  {
    id: "deep-research-max-preview-04-2026",
    name: "Deep Research Max Preview (Apr-21-2026)",
    contextWindow: 131072,
    reasoning: true,
  },
  {
    id: "deep-research-preview-04-2026",
    name: "Deep Research Preview (Apr-21-2026)",
    contextWindow: 131072,
    reasoning: true,
  },
  {
    id: "gemini-2.5-computer-use-preview-10-2025",
    name: "Gemini 2.5 Computer Use Preview 10-2025",
    contextWindow: 131072,
    reasoning: true,
  },
  { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", contextWindow: 1048576, reasoning: true },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash-Lite",
    contextWindow: 1048576,
    reasoning: true,
  },
  { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", contextWindow: 1048576, reasoning: true },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    contextWindow: 1048576,
    reasoning: true,
  },
  {
    id: "gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    contextWindow: 1048576,
    reasoning: true,
  },
  {
    id: "gemini-3.1-flash-lite-image",
    name: "Nano Banana 2 Lite",
    contextWindow: 65536,
    reasoning: true,
  },
  {
    id: "gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    contextWindow: 1048576,
    reasoning: true,
  },
  {
    id: "gemini-3.1-flash-live-preview",
    name: "Gemini 3.1 Flash Live Preview",
    contextWindow: 131072,
    reasoning: true,
  },
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    contextWindow: 1048576,
    reasoning: true,
  },
  {
    id: "gemini-3.1-pro-preview-customtools",
    name: "Gemini 3.1 Pro Preview Custom Tools",
    contextWindow: 1048576,
    reasoning: true,
  },
  { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash", contextWindow: 1048576, reasoning: true },
  {
    id: "gemini-3.5-flash-lite",
    name: "Gemini 3.5 Flash Lite",
    contextWindow: 1048576,
    reasoning: true,
  },
  { id: "gemini-3.6-flash", name: "Gemini 3.6 Flash", contextWindow: 1048576, reasoning: true },
  { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash", contextWindow: 1048576, reasoning: true },
  {
    id: "gemini-flash-latest",
    name: "Gemini Flash Latest",
    contextWindow: 1048576,
    reasoning: true,
  },
  {
    id: "gemini-flash-lite-latest",
    name: "Gemini Flash-Lite Latest",
    contextWindow: 1048576,
    reasoning: true,
  },
  {
    id: "gemini-robotics-er-1.6-preview",
    name: "Gemini Robotics-ER 1.6 Preview",
    contextWindow: 131072,
    reasoning: true,
  },
  { id: "gemma-4-26b-a4b-it", name: "Gemma 4 26B A4B IT", contextWindow: 262144, reasoning: true },
  { id: "gemma-4-31b-it", name: "Gemma 4 31B IT", contextWindow: 262144, reasoning: true },
];

export const deepseekModels: PiModelOption[] = [
  { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", contextWindow: 1000000, reasoning: true },
  { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", contextWindow: 1000000, reasoning: true },
];

export const openrouterModels: PiModelOption[] = [
  { id: "anthropic/claude-opus-5", name: "Claude Opus 5", contextWindow: 1000000, reasoning: true },
  {
    id: "anthropic/claude-sonnet-5",
    name: "Anthropic: Claude Sonnet 5",
    contextWindow: 1000000,
    reasoning: true,
  },
  {
    id: "anthropic/claude-haiku-4.5",
    name: "Anthropic: Claude Haiku 4.5",
    contextWindow: 200000,
    reasoning: true,
  },
  { id: "openai/gpt-5.5", name: "OpenAI: GPT-5.5", contextWindow: 1050000, reasoning: true },
  {
    id: "openai/gpt-5.5-pro",
    name: "OpenAI: GPT-5.5 Pro",
    contextWindow: 1050000,
    reasoning: true,
  },
  { id: "openai/gpt-5.2", name: "OpenAI: GPT-5.2", contextWindow: 400000, reasoning: true },
  {
    id: "google/gemini-3.7-flash",
    name: "Google: Gemini 3.7 Flash",
    contextWindow: 1048576,
    reasoning: true,
  },
  {
    id: "google/gemini-3.1-pro-preview",
    name: "Google: Gemini 3.1 Pro Preview",
    contextWindow: 1048576,
    reasoning: true,
  },
  {
    id: "deepseek/deepseek-v4-pro",
    name: "DeepSeek: DeepSeek V4 Pro",
    contextWindow: 1048576,
    reasoning: true,
  },
  {
    id: "deepseek/deepseek-chat",
    name: "DeepSeek: DeepSeek V3",
    contextWindow: 128000,
    reasoning: false,
  },
  { id: "x-ai/grok-4.6", name: "SpaceXAI: Grok 4.6", contextWindow: 500000, reasoning: true },
  {
    id: "moonshotai/kimi-k3",
    name: "MoonshotAI: Kimi K3",
    contextWindow: 1048576,
    reasoning: true,
  },
  { id: "qwen/qwen3.8-max", name: "Qwen: Qwen3.8 Max", contextWindow: 1000000, reasoning: true },
  {
    id: "mistralai/mistral-large-2512",
    name: "Mistral: Mistral Large 3 2512",
    contextWindow: 262144,
    reasoning: false,
  },
  {
    id: "meta-llama/llama-4-maverick",
    name: "Meta: Llama 4 Maverick",
    contextWindow: 1048576,
    reasoning: false,
  },
];

export const mistralModels: PiModelOption[] = [
  { id: "codestral-latest", name: "Codestral (latest)", contextWindow: 256000, reasoning: false },
  { id: "devstral-2512", name: "Devstral 2", contextWindow: 262144, reasoning: false },
  { id: "devstral-latest", name: "Devstral 2", contextWindow: 262144, reasoning: false },
  { id: "devstral-medium-2507", name: "Devstral Medium", contextWindow: 128000, reasoning: false },
  {
    id: "devstral-medium-latest",
    name: "Devstral 2 (latest)",
    contextWindow: 262144,
    reasoning: false,
  },
  {
    id: "devstral-small-2505",
    name: "Devstral Small 2505",
    contextWindow: 128000,
    reasoning: false,
  },
  { id: "devstral-small-2507", name: "Devstral Small", contextWindow: 128000, reasoning: false },
  {
    id: "labs-devstral-small-2512",
    name: "Devstral Small 2",
    contextWindow: 256000,
    reasoning: false,
  },
  {
    id: "magistral-medium-latest",
    name: "Magistral Medium (latest)",
    contextWindow: 128000,
    reasoning: true,
  },
  { id: "magistral-small", name: "Magistral Small", contextWindow: 128000, reasoning: true },
  {
    id: "ministral-3b-latest",
    name: "Ministral 3B (latest)",
    contextWindow: 128000,
    reasoning: false,
  },
  {
    id: "ministral-8b-latest",
    name: "Ministral 8B (latest)",
    contextWindow: 128000,
    reasoning: false,
  },
  { id: "mistral-large-2411", name: "Mistral Large 2.1", contextWindow: 131072, reasoning: false },
  { id: "mistral-large-2512", name: "Mistral Large 3", contextWindow: 262144, reasoning: false },
  {
    id: "mistral-large-latest",
    name: "Mistral Large (latest)",
    contextWindow: 262144,
    reasoning: false,
  },
  { id: "mistral-medium-2505", name: "Mistral Medium 3", contextWindow: 131072, reasoning: false },
  {
    id: "mistral-medium-2508",
    name: "Mistral Medium 3.1",
    contextWindow: 262144,
    reasoning: false,
  },
  { id: "mistral-medium-2604", name: "Mistral Medium 3.5", contextWindow: 262144, reasoning: true },
  { id: "mistral-medium-3.5", name: "Mistral Medium 3.5", contextWindow: 262144, reasoning: true },
  {
    id: "mistral-medium-latest",
    name: "Mistral Medium (latest)",
    contextWindow: 262144,
    reasoning: true,
  },
  { id: "mistral-nemo", name: "Mistral Nemo", contextWindow: 128000, reasoning: false },
  { id: "mistral-small-2506", name: "Mistral Small 3.2", contextWindow: 128000, reasoning: false },
  { id: "mistral-small-2603", name: "Mistral Small 4", contextWindow: 256000, reasoning: true },
  {
    id: "mistral-small-latest",
    name: "Mistral Small (latest)",
    contextWindow: 256000,
    reasoning: true,
  },
  { id: "open-mistral-7b", name: "Mistral 7B", contextWindow: 8000, reasoning: false },
  { id: "open-mistral-nemo", name: "Open Mistral Nemo", contextWindow: 128000, reasoning: false },
  { id: "open-mixtral-8x22b", name: "Mixtral 8x22B", contextWindow: 64000, reasoning: false },
  { id: "open-mixtral-8x7b", name: "Mixtral 8x7B", contextWindow: 32000, reasoning: false },
  { id: "pixtral-12b", name: "Pixtral 12B", contextWindow: 128000, reasoning: false },
  {
    id: "pixtral-large-latest",
    name: "Pixtral Large (latest)",
    contextWindow: 128000,
    reasoning: false,
  },
  {
    id: "voxtral-small-latest",
    name: "Voxtral Small (latest)",
    contextWindow: 32000,
    reasoning: false,
  },
];

export const groqModels: PiModelOption[] = [
  { id: "llama-3.1-8b-instant", name: "Llama 3.1 8B", contextWindow: 131072, reasoning: false },
  { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B", contextWindow: 131072, reasoning: false },
  { id: "openai/gpt-oss-120b", name: "GPT OSS 120B", contextWindow: 131072, reasoning: true },
  { id: "openai/gpt-oss-20b", name: "GPT OSS 20B", contextWindow: 131072, reasoning: true },
  {
    id: "openai/gpt-oss-safeguard-20b",
    name: "Safety GPT OSS 20B",
    contextWindow: 131072,
    reasoning: true,
  },
  { id: "qwen/qwen3.6-27b", name: "Qwen3.6 27B", contextWindow: 131072, reasoning: true },
];

export const xaiModels: PiModelOption[] = [
  { id: "grok-4.3", name: "Grok 4.3", contextWindow: 1000000, reasoning: true },
  { id: "grok-4.5", name: "Grok 4.5", contextWindow: 500000, reasoning: true },
  { id: "grok-4.6", name: "Grok 4.6", contextWindow: 500000, reasoning: true },
  { id: "grok-build-0.1", name: "Grok Build 0.1", contextWindow: 256000, reasoning: true },
];

export const PI_PROVIDERS: PiProviderOption[] = [
  { value: "anthropic", label: "Anthropic", envVar: "ANTHROPIC_API_KEY", models: anthropicModels },
  { value: "openai", label: "OpenAI", envVar: "OPENAI_API_KEY", models: openaiModels },
  { value: "google", label: "Google", envVar: "GOOGLE_API_KEY", models: googleModels },
  { value: "deepseek", label: "DeepSeek", envVar: "DEEPSEEK_API_KEY", models: deepseekModels },
  {
    value: "openrouter",
    label: "OpenRouter",
    envVar: "OPENROUTER_API_KEY",
    models: openrouterModels,
  },
  { value: "mistral", label: "Mistral", envVar: "MISTRAL_API_KEY", models: mistralModels },
  { value: "groq", label: "Groq", envVar: "GROQ_API_KEY", models: groqModels },
  { value: "xai", label: "xAI", envVar: "XAI_API_KEY", models: xaiModels },
];
